ALTER TABLE clients ADD COLUMN IF NOT EXISTS project_type TEXT DEFAULT 'contracted';
ALTER TABLE clients ADD COLUMN IF NOT EXISTS default_lg_pct NUMERIC DEFAULT 60;
ALTER TABLE clients ADD COLUMN IF NOT EXISTS default_cn_pct NUMERIC DEFAULT 40;
