
ALTER TABLE crm_pipeline
  ADD COLUMN IF NOT EXISTS rating TEXT DEFAULT 'normal',
  ADD COLUMN IF NOT EXISTS preferences TEXT,
  ADD COLUMN IF NOT EXISTS workers_seasonal INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS workers_permanent INTEGER DEFAULT 0;
